name: base
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch==1.12.1
  - torchvision==0.13.1
  - cudatoolkit=11.3
  - numpy==1.22.3
  - pandas==1.4.4
  - scipy==1.7.3
  - scikit-learn==1.1.3
  - ipython==8.10.0
  - jupyter==1.0.0
  - pyyaml
  - pip
  - pip:
    - tqdm==4.66.1
